### ISSUE TITLE
As apostilas da Caelum se encaixam no propósito deste repositório ?

### ISSUE THREAD

**Issue by RyanFilho** [cerebrobr/livros#8]
A instituição de ensino Caelum distribui apostilas livres sobre diversas linguagens de programação, antes de fazer um fork queria perguntar se essas apostilas se encaixam no propósito deste repositório ? @cerebrobr/editores

**Comment by RyanFilho** [comment]
Segue o link das apostilas gratuitas da Caelum : 
https://www.caelum.com.br/apostilas/

**Comment by thulioph** [comment]
@RyanFilho acredito que sim cara, toda ajuda é bem-vinda. Por mim é +1

**Comment by thulioph** [comment]
Cc: @cerebrobr/editores

**Comment by fdaciuk** [comment]
Acho válido! +1

**Comment by RyanFilho** [comment]
Ok! Vou fazer o pull request.
